import { Boss } from "./types";

export const BOSSES: Boss[] = [
  {
    label: "Cortondo Gym (Katy)",
    name: "Katy",
    ace: "Teddiursa",
    level: 15,
    tera: "bug",
  },
  {
    label: "Artazon Gym (Brassius)",
    name: "Brassius",
    ace: "Sudowoodo",
    level: 17,
    tera: "grass",
  },
  {
    label: "Team Star Segin (Giacomo)",
    name: "Giacomo",
    ace: "Pawniard",
    level: 21,
    tera: "dark",
  },
  {
    label: "Levincia Gym (Iono)",
    name: "Iono",
    ace: "Mismagius",
    level: 24,
    tera: "electric",
  },
  {
    label: "Team Star Schedar (Mela)",
    name: "Mela",
    ace: "Torkoal",
    level: 27,
    tera: "fire",
  },
  {
    label: "Cascarrafa Gym (Kofu)",
    name: "Kofu",
    ace: "Crabominable",
    level: 30,
    tera: "water",
  },
  {
    label: "Team Star Navi (Atticus)",
    name: "Atticus",
    ace: "Revavroom",
    level: 33,
    tera: "poison",
  },
  {
    label: "Medali Gym (Larry)",
    name: "Larry",
    ace: "Staraptor",
    level: 36,
    tera: "normal",
  },
  {
    label: "Montenevera Gym (Ryme)",
    name: "Ryme",
    ace: "Toxtricity",
    level: 42,
    tera: "ghost",
  },
  {
    label: "Alfornada Gym (Tulip)",
    name: "Tulip",
    ace: "Florges",
    level: 45,
    tera: "psychic",
  },
  {
    label: "Glaseado Gym (Grusha)",
    name: "Grusha",
    ace: "Altaria",
    level: 48,
    tera: "ice",
  },
  {
    label: "Team Star Ruchbah (Ortega)",
    name: "Ortega",
    ace: "Dachsbun",
    level: 51,
    tera: "fairy",
  },
  {
    label: "Team Star Caph (Eri)",
    name: "Eri",
    ace: "Annihilape",
    level: 56,
    tera: "fighting",
  },
  {
    label: "Elite Four Rika",
    name: "Rika",
    ace: "Clodsire",
    level: 61,
    tera: "ground",
  },
  {
    label: "Elite Four Poppy",
    name: "Poppy",
    ace: "Tinkaton",
    level: 61,
    tera: "steel",
  },
  {
    label: "Elite Four Larry",
    name: "Larry (E4)",
    ace: "Flamigo",
    level: 61,
    tera: "flying",
  },
  {
    label: "Elite Four Hassel",
    name: "Hassel",
    ace: "Baxcalibur",
    level: 61,
    tera: "dragon",
  },
  {
    label: "Top Champion Geeta",
    name: "Geeta",
    ace: "Glimmora",
    level: 62,
    tera: "rock",
  },
  {
    label: "Team Star Penny",
    name: "Penny",
    ace: "Sylveon",
    level: 63,
    tera: "fairy",
  },
];
