export const LOCAL_ENCOUNTER_LOCATIONS: Record<string, string[]> = {
  Alomomola: [
    "North Province (Area One)",
    "North Province (Area Three)",
    "North Paldean Sea",
  ],
  Altaria: [
    "South Province (Area Six)",
    "North Province (Area One)",
    "Glaseado Mountain",
  ],
  Amoonguss: [
    "North Province (Area One)",
    "North Province (Area Two)",
    "Glaseado Mountain",
  ],
  Ampharos: ["South Province (Area Six)", "North Province (Area One)"],
  Applin: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "North Province (Area One)",
    "Tagtree Thicket",
  ],
  Arboliva: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Arcanine: ["North Province (Area Two)"],
  Arctibax: ["North Province (Area One)", "North Province (Area Three)"],
  Arrokuda: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Avalugg: ["North Paldean Sea", "Glaseado Mountain"],
  Axew: [
    "South Province (Area Five)",
    "North Province (Area One)",
    "Great Crater of Paldea",
  ],
  Azumarill: [
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Casseroya Lake",
  ],
  Azurill: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "West Paldean Sea",
  ],
  Bagon: ["South Province (Area Five)"],
  Banette: ["South Province (Area Six)", "Glaseado Mountain"],
  Barboach: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "Casseroya Lake",
  ],
  Barraskewda: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "Asado Desert",
    "West Paldean Sea",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "East Paldean Sea",
    "North Province (Area Two)",
    "North Paldean Sea",
    "Casseroya Lake",
  ],
  Basculin: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Beartic: ["North Province (Area Three)", "Glaseado Mountain"],
  Bellibolt: [
    "West Province (Area Two)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Glaseado Mountain",
  ],
  Bergmite: ["North Paldean Sea", "Glaseado Mountain"],
  Bisharp: ["North Province (Area Two)", "Great Crater of Paldea"],
  Blissey: [
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
  ],
  Bombirdier: [
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "West Paldean Sea",
  ],
  Bonsly: ["South Province (Area One)", "South Province (Area Two)"],
  Bounsweet: [
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area Three)",
  ],
  Brambleghast: ["North Province (Area One)", "Glaseado Mountain"],
  Bramblin: ["Asado Desert", "East Province (Area Three)"],
  Braviary: [
    "North Province (Area One)",
    "North Province (Area Two)",
    "Great Crater of Paldea",
  ],
  Breloom: ["West Province (Area Three)"],
  Bronzong: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "Glaseado Mountain",
    "Great Crater of Paldea",
  ],
  Bronzor: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "East Province (Area One)",
  ],
  "Brute Bonnet": ["Great Crater of Paldea"],
  Bruxish: ["South Paldean Sea", "West Paldean Sea", "East Paldean Sea"],
  Buizel: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "South Paldean Sea",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "West Paldean Sea",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "East Paldean Sea",
  ],
  Cacnea: ["Asado Desert"],
  Camerupt: ["North Province (Area Two)", "Great Crater of Paldea"],
  Capsakid: ["West Province (Area One)", "West Province (Area Three)"],
  Carkol: ["East Province (Area Three)"],
  Cetitan: [
    "North Province (Area One)",
    "Glaseado Mountain",
    "Great Crater of Paldea",
  ],
  Cetoddle: [
    "North Province (Area One)",
    "North Province (Area Three)",
    "Glaseado Mountain",
  ],
  Chansey: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "Asado Desert",
    "West Paldean Sea",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Great Crater of Paldea",
  ],
  Charcadet: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "Tagtree Thicket",
  ],
  Chewtle: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Paldean Sea",
    "East Province (Area One)",
    "East Province (Area Two)",
  ],
  Clauncher: ["West Paldean Sea", "East Paldean Sea", "North Paldean Sea"],
  Clawitzer: ["South Paldean Sea", "North Paldean Sea"],
  Clodsire: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Cloyster: ["West Paldean Sea", "East Paldean Sea", "North Paldean Sea"],
  Combee: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Four)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "East Province (Area Two)",
    "North Province (Area One)",
  ],
  Copperajah: [
    "South Province (Area Six)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Glaseado Mountain",
  ],
  Corviknight: ["Great Crater of Paldea"],
  Corvisquire: [
    "South Province (Area Five)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Crabominable: ["Great Crater of Paldea"],
  Crabrawler: [
    "South Province (Area Three)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Paldean Sea",
    "East Province (Area One)",
    "Glaseado Mountain",
  ],
  Croagunk: [
    "South Province (Area Five)",
    "West Province (Area Two)",
    "Casseroya Lake",
  ],
  Cryogonal: ["Great Crater of Paldea"],
  Cubchoo: [
    "North Province (Area One)",
    "North Province (Area Three)",
    "Glaseado Mountain",
  ],
  Cufant: ["East Province (Area Two)", "East Province (Area Three)"],
  Cyclizar: ["West Province (Area Two)", "East Province (Area Two)"],
  Dachsbun: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Six)",
    "South Paldean Sea",
    "West Province (Area Three)",
    "East Province (Area Three)",
  ],
  Dedenne: ["West Province (Area Three)", "North Province (Area One)"],
  Deerling: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
  ],
  Deino: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
  ],
  Delibird: [
    "North Province (Area One)",
    "North Province (Area Three)",
    "Glaseado Mountain",
  ],
  Diglett: [
    "South Province (Area Two)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "East Province (Area One)",
  ],
  Ditto: ["West Province (Area Two)", "West Province (Area Three)"],
  Dolliv: [
    "East Province (Area Two)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Tagtree Thicket",
  ],
  Dondozo: ["Casseroya Lake"],
  Donphan: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "Asado Desert",
    "Great Crater of Paldea",
  ],
  Dragalge: ["North Paldean Sea"],
  Dragonair: ["Casseroya Lake"],
  Drakloak: [
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Glaseado Mountain",
  ],
  Dratini: [
    "South Province (Area Six)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "Casseroya Lake",
  ],
  Drednaw: [
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area Two)",
    "Asado Desert",
    "West Paldean Sea",
    "East Province (Area One)",
    "East Province (Area Two)",
    "Casseroya Lake",
  ],
  Dreepy: [
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Drifblim: [
    "South Province (Area Four)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "Glaseado Mountain",
  ],
  Drifloon: [
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "Great Crater of Paldea",
  ],
  Drowzee: [
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
  ],
  Dugtrio: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Dunsparce: ["South Province (Area Four)", "Great Crater of Paldea"],
  Eelektrik: [
    "South Province (Area Four)",
    "South Province (Area Six)",
    "South Paldean Sea",
    "West Province (Area One)",
    "West Paldean Sea",
    "North Paldean Sea",
  ],
  Eevee: ["South Province (Area Two)", "West Province (Area Three)"],
  Eiscue: [
    "North Province (Area One)",
    "North Province (Area Three)",
    "North Paldean Sea",
  ],
  Electrode: ["West Province (Area Three)", "East Province (Area Two)"],
  Espathra: [
    "South Province (Area Four)",
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "Casseroya Lake",
    "Glaseado Mountain",
  ],
  Espeon: ["North Province (Area Three)", "Glaseado Mountain"],
  Falinks: [
    "West Province (Area One)",
    "West Province (Area Three)",
    "North Province (Area One)",
  ],
  Farigiraf: ["Great Crater of Paldea"],
  Fidough: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Six)",
    "South Paldean Sea",
    "West Province (Area Three)",
    "East Province (Area Three)",
  ],
  Finizen: [
    "South Paldean Sea",
    "West Paldean Sea",
    "East Paldean Sea",
    "North Paldean Sea",
  ],
  Finneon: ["West Paldean Sea", "North Paldean Sea"],
  Flaaffy: ["South Province (Area Six)", "West Province (Area Three)"],
  Flabebe: [
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "East Province (Area One)",
  ],
  Flamigo: ["Casseroya Lake", "Glaseado Mountain"],
  Flareon: ["West Province (Area Three)", "Glaseado Mountain"],
  Fletchinder: [
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
  ],
  Fletchling: ["South Province (Area One)", "South Province (Area Two)"],
  Flittle: [
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Floatzel: [
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
  ],
  Floette: [
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
  ],
  Florges: ["North Province (Area Three)"],
  "Flutter Mane": ["Great Crater of Paldea"],
  Fomantis: [
    "South Province (Area Five)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Foongus: [
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area Two)",
    "Tagtree Thicket",
  ],
  Forretress: ["Casseroya Lake"],
  Fraxure: [
    "South Province (Area Five)",
    "North Province (Area One)",
    "Great Crater of Paldea",
  ],
  Frigibax: ["Great Crater of Paldea"],
  Froslass: ["South Province (Area Five)", "Asado Desert", "West Paldean Sea"],
  Frosmoth: ["Casseroya Lake", "Glaseado Mountain"],
  Gabite: [
    "South Province (Area Six)",
    "North Province (Area One)",
    "Glaseado Mountain",
  ],
  Gallade: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "Glaseado Mountain",
  ],
  Gardevoir: ["Great Crater of Paldea"],
  Garganacl: ["Great Crater of Paldea"],
  Gastly: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  "Gastrodon (East)": [
    "South Province (Area Five)",
    "East Province (Area One)",
    "East Province (Area Three)",
  ],
  "Gastrodon (West)": [
    "South Province (Area Four)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "North Province (Area One)",
  ],
  Gible: [
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
  ],
  Gimmighoul: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Girafarig: ["West Province (Area Two)", "Tagtree Thicket"],
  Glaceon: ["Great Crater of Paldea"],
  Glalie: [
    "South Province (Area Four)",
    "West Province (Area One)",
    "West Province (Area Two)",
  ],
  Glimmet: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "Glaseado Mountain",
  ],
  Glimmora: ["Great Crater of Paldea"],
  Gogoat: [
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Golduck: [
    "North Province (Area One)",
    "North Province (Area Three)",
    "North Paldean Sea",
  ],
  Goomy: [
    "South Province (Area One)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Gothita: ["East Province (Area Three)", "Tagtree Thicket"],
  Gothitelle: ["South Province (Area Six)"],
  Gothorita: ["South Province (Area Six)"],
  Grafaiai: ["North Province (Area Three)"],
  "Great Tusk": ["Great Crater of Paldea"],
  Greavard: [
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "Tagtree Thicket",
  ],
  Greedent: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "Glaseado Mountain",
  ],
  Grimer: ["West Province (Area Two)", "West Paldean Sea"],
  Growlithe: ["South Province (Area Three)", "East Province (Area Two)"],
  Grumpig: [
    "North Province (Area One)",
    "North Province (Area Two)",
    "Glaseado Mountain",
  ],
  Gulpin: ["South Province (Area Three)", "West Province (Area Three)"],
  Gumshoos: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "North Province (Area One)",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Gyarados: [
    "South Paldean Sea",
    "West Paldean Sea",
    "East Paldean Sea",
    "North Paldean Sea",
  ],
  Happiny: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "West Province (Area One)",
  ],
  Hariyama: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area Three)",
    "North Province (Area One)",
  ],
  Hatenna: ["South Province (Area Four)", "West Province (Area Two)"],
  Hattrem: ["South Province (Area Six)", "Casseroya Lake", "Tagtree Thicket"],
  Haunter: ["North Province (Area One)", "Glaseado Mountain"],
  Hawlucha: [
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Glaseado Mountain",
  ],
  Heracross: [
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Glaseado Mountain",
  ],
  Hippopotas: ["Asado Desert"],
  Honchkrow: [
    "South Province (Area Six)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "Casseroya Lake",
    "Glaseado Mountain",
  ],
  Hoppip: ["South Province (Area One)", "South Province (Area Two)"],
  Houndoom: ["North Province (Area Two)"],
  Houndour: ["South Province (Area One)", "South Province (Area Five)"],
  Houndstone: [
    "South Province (Area Six)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Glaseado Mountain",
  ],
  Hypno: ["Great Crater of Paldea"],
  Igglybuff: ["South Province (Area Two)"],
  Impidimp: ["North Province (Area Three)"],
  "Indeedee (F)": ["North Province (Area One)", "North Province (Area Two)"],
  "Indeedee (M)": ["North Province (Area One)", "North Province (Area Two)"],
  "Iron Bundle": ["Great Crater of Paldea"],
  "Iron Hands": ["Great Crater of Paldea"],
  "Iron Jugulis": ["Great Crater of Paldea"],
  "Iron Moth": ["Great Crater of Paldea"],
  "Iron Thorns": ["Great Crater of Paldea"],
  "Iron Treads": ["Great Crater of Paldea"],
  "Iron Valiant": ["Great Crater of Paldea"],
  Jigglypuff: ["South Province (Area Two)", "West Province (Area Three)"],
  Jolteon: ["West Province (Area Three)", "Casseroya Lake"],
  Jumpluff: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Glaseado Mountain",
  ],
  Kilowattrel: ["West Paldean Sea", "East Paldean Sea", "North Paldean Sea"],
  Kirlia: ["West Province (Area Two)", "West Paldean Sea", "Glaseado Mountain"],
  Klawf: ["South Province (Area Three)"],
  Klefki: ["Great Crater of Paldea"],
  Komala: [
    "South Province (Area Four)",
    "West Province (Area Two)",
    "Asado Desert",
    "West Paldean Sea",
    "East Province (Area One)",
    "Tagtree Thicket",
  ],
  Kricketot: ["South Province (Area Two)", "North Province (Area One)"],
  Kricketune: ["North Province (Area One)"],
  Larvesta: ["Asado Desert"],
  Larvitar: [
    "South Province (Area Three)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "East Province (Area Three)",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Leafeon: ["West Province (Area Three)", "Casseroya Lake"],
  Lechonk: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "South Paldean Sea",
    "West Province (Area One)",
    "West Province (Area Two)",
    "Asado Desert",
    "Glaseado Mountain",
  ],
  Lilligant: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Litleo: [
    "South Province (Area Five)",
    "East Province (Area One)",
    "Tagtree Thicket",
  ],
  Lokix: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "Asado Desert",
    "West Paldean Sea",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
  ],
  Lucario: [
    "South Province (Area Four)",
    "South Province (Area Six)",
    "North Province (Area One)",
    "North Province (Area Two)",
  ],
  Lumineon: ["West Paldean Sea", "North Paldean Sea"],
  Lurantis: [
    "South Province (Area Five)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Luvdisc: ["South Paldean Sea", "West Paldean Sea", "East Paldean Sea"],
  Luxio: ["South Province (Area Five)"],
  Luxray: ["North Province (Area Two)"],
  "Lycanroc (Dusk)": ["North Province (Area One)"],
  "Lycanroc (Midday)": [
    "South Province (Area Six)",
    "East Province (Area Three)",
    "Glaseado Mountain",
    "Great Crater of Paldea",
  ],
  "Lycanroc (Midnight)": ["Great Crater of Paldea"],
  Mabosstiff: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Casseroya Lake",
  ],
  Magikarp: [
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Paldean Sea",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
  ],
  Magnemite: ["East Province (Area Two)", "East Province (Area Three)"],
  Magneton: ["Great Crater of Paldea"],
  Magnezone: ["Great Crater of Paldea"],
  Makuhita: [
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Paldean Sea",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Mankey: ["South Province (Area Five)", "West Province (Area One)"],
  Mareanie: [
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Mareep: ["South Province (Area Two)"],
  Marill: ["East Province (Area Two)"],
  Maschiff: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "West Province (Area Two)",
    "West Province (Area Three)",
  ],
  Masquerain: [
    "South Province (Area Four)",
    "South Province (Area Five)",
    "Tagtree Thicket",
  ],
  Medicham: [
    "South Province (Area Four)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "Glaseado Mountain",
  ],
  Meditite: [
    "South Province (Area Four)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "Glaseado Mountain",
  ],
  Meowth: [
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area Three)",
  ],
  Mimikyu: ["East Province (Area Two)", "Tagtree Thicket", "Glaseado Mountain"],
  Misdreavus: [
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Mismagius: [
    "South Province (Area Six)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "Casseroya Lake",
    "Glaseado Mountain",
  ],
  Morgrem: ["North Province (Area Three)"],
  Mudbray: [
    "South Province (Area One)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "Glaseado Mountain",
  ],
  Mudsdale: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "Casseroya Lake",
  ],
  Murkrow: [
    "South Province (Area One)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Nacli: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Naclstack: [
    "South Province (Area Six)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Glaseado Mountain",
  ],
  Noibat: [
    "West Province (Area Two)",
    "North Province (Area One)",
    "North Province (Area Two)",
  ],
  Noivern: ["North Province (Area One)", "North Province (Area Two)"],
  Numel: ["West Province (Area One)"],
  Nymble: ["South Province (Area Three)", "West Province (Area One)"],
  Oinkologne: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Three)",
    "Glaseado Mountain",
    "Tagtree Thicket",
  ],
  Oranguru: [
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Tagtree Thicket",
  ],
  "Oricorio (Baile)": [
    "South Province (Area Three)",
    "East Province (Area One)",
  ],
  "Oricorio (Pom-Pom)": ["South Province (Area One)"],
  Orthworm: [
    "South Paldean Sea",
    "West Province (Area One)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Three)",
  ],
  Pachirisu: [
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area Two)",
  ],
  "Paldean Tauros (Fighting)": [
    "West Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
  ],
  "Paldean Tauros (Fighting/Fire)": [
    "West Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
  ],
  "Paldean Tauros (Fighting/Water)": [
    "West Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
  ],
  "Paldean Wooper": [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
  ],
  Palossand: [
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "Asado Desert",
    "Casseroya Lake",
  ],
  Passimian: [
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Tagtree Thicket",
  ],
  Pawmi: ["South Province (Area One)", "South Province (Area Three)"],
  Pawmo: [
    "South Province (Area One)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Pawniard: [
    "South Province (Area Five)",
    "East Province (Area One)",
    "Casseroya Lake",
  ],
  Pelipper: [
    "South Province (Area One)",
    "South Paldean Sea",
    "West Province (Area One)",
    "West Province (Area Two)",
    "Asado Desert",
    "North Province (Area One)",
    "North Province (Area Two)",
  ],
  Persian: ["West Province (Area Three)"],
  Petilil: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Phanpy: [
    "South Province (Area Four)",
    "West Province (Area One)",
    "West Province (Area Three)",
  ],
  Pichu: ["South Province (Area Two)"],
  Pikachu: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "West Province (Area Three)",
    "East Province (Area One)",
  ],
  Pincurchin: [
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area One)",
    "North Province (Area One)",
    "North Province (Area Three)",
  ],
  Pineco: [
    "South Province (Area Three)",
    "South Province (Area Four)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "Tagtree Thicket",
  ],
  Primeape: [
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
  ],
  Psyduck: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Three)",
    "Tagtree Thicket",
  ],
  Pupitar: ["South Province (Area Six)"],
  Pyroar: [
    "South Province (Area Five)",
    "East Province (Area One)",
    "Tagtree Thicket",
  ],
  Qwilfish: [
    "South Paldean Sea",
    "West Paldean Sea",
    "East Paldean Sea",
    "North Paldean Sea",
  ],
  Raichu: ["Casseroya Lake"],
  Ralts: ["South Province (Area One)"],
  Rellor: ["Asado Desert"],
  Revavroom: [
    "East Province (Area Three)",
    "North Province (Area One)",
    "Glaseado Mountain",
  ],
  Riolu: ["South Province (Area Four)"],
  "Roaring Moon": ["Great Crater of Paldea"],
  Rockruff: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "East Province (Area One)",
  ],
  Rolycoly: ["East Province (Area Three)"],
  Rookidee: [
    "South Province (Area Three)",
    "South Province (Area Five)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Rotom: ["West Province (Area Two)", "West Province (Area Three)"],
  Rufflet: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Sableye: [
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Glaseado Mountain",
    "Tagtree Thicket",
  ],
  Salandit: [
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "East Province (Area Two)",
    "Tagtree Thicket",
  ],
  Salazzle: ["South Province (Area Six)", "East Province (Area Three)"],
  Sandile: ["Asado Desert"],
  "Sandy Shocks": ["Great Crater of Paldea"],
  Sandygast: [
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "Asado Desert",
  ],
  Sawsbuck: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
  ],
  Scatterbug: ["South Province (Area One)"],
  Scovillain: [
    "South Province (Area Six)",
    "East Province (Area Three)",
    "North Province (Area Three)",
    "Tagtree Thicket",
  ],
  "Scream Tail": ["Great Crater of Paldea"],
  Scyther: [
    "South Province (Area Four)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Three)",
  ],
  Seviper: ["South Province (Area Three)", "South Province (Area Five)"],
  Shelgon: ["South Province (Area Six)"],
  Shellder: [
    "South Paldean Sea",
    "West Paldean Sea",
    "East Paldean Sea",
    "North Paldean Sea",
  ],
  "Shellos (East)": [
    "South Province (Area Five)",
    "East Province (Area One)",
    "East Province (Area Three)",
  ],
  "Shellos (West)": [
    "South Province (Area Four)",
    "South Province (Area Six)",
    "West Province (Area One)",
  ],
  Shinx: ["South Province (Area Three)"],
  Shroodle: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "Tagtree Thicket",
  ],
  Shroomish: ["South Province (Area Five)", "West Province (Area One)"],
  Shuppet: [
    "South Province (Area Three)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Silicobra: ["Asado Desert", "East Province (Area One)", "Tagtree Thicket"],
  Sinistea: ["South Province (Area Six)", "East Province (Area One)"],
  Skiddo: [
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Skiploom: [
    "South Province (Area Five)",
    "East Province (Area One)",
    "East Province (Area Two)",
  ],
  Skrelp: [
    "South Paldean Sea",
    "West Paldean Sea",
    "East Paldean Sea",
    "North Paldean Sea",
  ],
  Skuntank: ["Casseroya Lake"],
  Skwovet: ["South Province (Area Two)", "South Province (Area Four)"],
  Slaking: ["Casseroya Lake"],
  Slakoth: ["South Province (Area Three)", "South Province (Area Five)"],
  Sliggoo: ["Casseroya Lake"],
  "Slither Wing": ["Great Crater of Paldea"],
  Slowbro: ["West Province (Area Two)", "East Province (Area Three)"],
  Slowpoke: [
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Three)",
    "Asado Desert",
    "Casseroya Lake",
  ],
  Smoliv: ["South Province (Area Two)"],
  Sneasel: [
    "North Province (Area One)",
    "Glaseado Mountain",
    "Great Crater of Paldea",
  ],
  Snom: ["West Province (Area Three)", "Casseroya Lake", "Tagtree Thicket"],
  Snorunt: ["North Province (Area One)", "Glaseado Mountain"],
  Snover: ["Great Crater of Paldea"],
  Spewpa: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
  ],
  Spidops: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "North Province (Area One)",
    "North Province (Area Three)",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Spoink: ["South Province (Area Three)"],
  Squawkabilly: [
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Stantler: ["South Province (Area Five)"],
  Staraptor: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "Casseroya Lake",
  ],
  Staravia: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "Casseroya Lake",
  ],
  Starly: [
    "South Province (Area Two)",
    "South Province (Area Four)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "Casseroya Lake",
  ],
  Steenee: ["East Province (Area One)"],
  Stonjourner: ["Asado Desert"],
  Stunky: ["South Province (Area Five)", "West Province (Area One)"],
  Sudowoodo: ["West Province (Area Three)", "Casseroya Lake"],
  Sunflora: [
    "South Province (Area Six)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Three)",
  ],
  Sunkern: ["South Province (Area One)", "South Province (Area Two)"],
  Surskit: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "East Province (Area One)",
  ],
  Swablu: [
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "Glaseado Mountain",
  ],
  Swalot: ["Casseroya Lake"],
  Sylveon: ["South Province (Area Six)", "West Province (Area Three)"],
  Tadbulb: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Talonflame: ["Great Crater of Paldea"],
  Tandemaus: ["South Province (Area Six)", "East Province (Area One)"],
  Tarountula: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Tatsugiri: ["Casseroya Lake"],
  Teddiursa: ["South Province (Area Five)", "East Province (Area One)"],
  Tinkatink: [
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "East Province (Area One)",
    "East Province (Area Three)",
  ],
  Tinkatuff: [
    "North Province (Area One)",
    "North Province (Area Two)",
    "Glaseado Mountain",
  ],
  Toedscool: [
    "South Province (Area One)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "West Province (Area Two)",
    "West Province (Area Three)",
    "Asado Desert",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area Three)",
    "Tagtree Thicket",
  ],
  Toedscruel: ["Casseroya Lake"],
  Torkoal: ["East Province (Area Three)"],
  Toxel: ["South Province (Area Four)", "South Province (Area Six)"],
  Toxicroak: [
    "South Province (Area Five)",
    "West Province (Area One)",
    "North Province (Area Three)",
  ],
  "Toxtricity (Amped)": [
    "South Province (Area Four)",
    "South Province (Area Six)",
  ],
  "Toxtricity (Low Key)": [
    "South Province (Area Four)",
    "South Province (Area Six)",
  ],
  Tropius: ["West Province (Area Three)", "Casseroya Lake"],
  Tynamo: [
    "South Province (Area Four)",
    "South Province (Area Six)",
    "South Paldean Sea",
    "West Province (Area One)",
    "West Province (Area Three)",
    "North Paldean Sea",
  ],
  Umbreon: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "North Province (Area Two)",
    "Glaseado Mountain",
  ],
  Ursaring: [
    "North Province (Area One)",
    "North Province (Area Two)",
    "Glaseado Mountain",
  ],
  Vaporeon: [
    "South Province (Area Six)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Varoom: ["West Province (Area Two)", "East Province (Area One)"],
  Veluza: ["Asado Desert", "Casseroya Lake"],
  Venomoth: [
    "East Province (Area One)",
    "East Province (Area Two)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "North Province (Area Three)",
    "Tagtree Thicket",
    "Glaseado Mountain",
  ],
  Venonat: [
    "East Province (Area One)",
    "East Province (Area Two)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "Tagtree Thicket",
  ],
  Vespiquen: [
    "South Province (Area Six)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
    "Glaseado Mountain",
  ],
  Vigoroth: [
    "South Province (Area Five)",
    "West Province (Area One)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Vivillon: [
    "South Province (Area Six)",
    "East Province (Area Two)",
    "East Province (Area Three)",
    "North Province (Area One)",
    "North Province (Area Two)",
  ],
  Volcarona: ["Great Crater of Paldea"],
  Voltorb: ["West Province (Area Three)", "East Province (Area Two)"],
  Wattrel: [
    "South Province (Area One)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "West Province (Area Three)",
  ],
  Weavile: ["North Province (Area One)", "Great Crater of Paldea"],
  Whiscash: [
    "South Province (Area Six)",
    "West Province (Area Three)",
    "East Province (Area Three)",
    "Casseroya Lake",
    "Tagtree Thicket",
  ],
  Wigglytuff: ["North Province (Area One)"],
  Wiglett: [
    "South Province (Area Five)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "Asado Desert",
    "West Paldean Sea",
  ],
  Wingull: [
    "South Province (Area One)",
    "South Paldean Sea",
    "West Province (Area One)",
    "West Province (Area Two)",
    "Asado Desert",
  ],
  Wugtrio: [
    "West Province (Area Two)",
    "West Province (Area Three)",
    "East Province (Area One)",
    "East Province (Area Two)",
    "North Province (Area One)",
  ],
  Yungoos: [
    "South Province (Area One)",
    "South Province (Area Two)",
    "South Province (Area Three)",
    "South Province (Area Four)",
    "South Province (Area Five)",
    "South Province (Area Six)",
    "West Province (Area One)",
    "West Province (Area Two)",
    "Asado Desert",
    "East Province (Area One)",
    "East Province (Area Two)",
    "East Province (Area Three)",
  ],
  Zangoose: ["South Province (Area Five)"],
  Zoroark: ["West Province (Area Three)", "Casseroya Lake", "Tagtree Thicket"],
  Zorua: ["West Province (Area Three)", "Tagtree Thicket"],
  Zweilous: [
    "North Province (Area One)",
    "North Province (Area Two)",
    "Glaseado Mountain",
  ],
};
